### ISSUE TITLE
how do i set the AutoLoad's player value?

### ISSUE THREAD

**Issue by dandan290** [abrasivetroop/adaptive-audio-player#1]
I've tried PlayerAutoLoad.player = "." on the player node but it didn't work, I've also tried using that but with "self" instead of "."
still didn't work.

**Comment by dandan290** [comment]
the game just crashes when i open it

**Comment by abrasivetroop** [comment]
Make sure you set player_autoload.gd as an autoload otherwise it won't work
Also by default its PlayerAutoload not PlayerAutoLoad
